### PR TITLE
Workflow update

### PR DESCRIPTION
**Pull request by Eathox**
When merged this PR will:
- Add names to actions using `actions-rs/cargo@v1`
- Add fancy test reporting to github actions

### CODE REVIEW

**Comment by Eathox** [comment]
I'm currently unsure of the test workflow behaviour if one of the rust test fails.

This requirers more testing, prob best to first merge the integration tests before this PR.

**Comment by nanderstabel** [comment]
I've reviewed and merged your integration tests PR, do you want to do more testing before merging this PR?

**Comment by Eathox** [comment]
Yep I did, all done now

**Comment by nanderstabel** [comment]
Nice!

**Review by nanderstabel — APPROVED** [review]

**Pull request merged**
